# Bayes's Theorem

#### The Cookie Problem

- Bowl 1: 30 vanilla, 10 chocolate cookies
- Bowl 2: 20 vanilla, 20 chocolate cookies

If we choose, at random, a bowl and a cookie from that bowl, drawing vanilla, what is the probability that it came from bowl 1?

We are looking for the conditional probability:

$$ P(B_1 \mid V) $$

However, what we get from the statement is:

$$ P(V \mid B_1) $$

and

$$ P(V \mid B_2) $$

Bayes's theorum tells us how they are related:

$$ P(B_1 \mid V) = \frac {P(B_1) \, P(V\mid B_1)} {P(V)} $$

So, in order to complete the equation, we need:

$$ P(V) $$

Which we can find, using the law of total probability:

$$ P(V) = P(B_1) \, P(V\mid B_1) \; + \; P(B_2) \, P(V \mid B_2) $$

Using what we know, we can fill it in:

$$ P(V) = (1/2) \, (3/4) \; + \; (1/2) \, (1/2) = (5/8) $$

So, using that new information, we can derive $$ P(B_1 \mid V) $$ by plugging in the numbers:

$$ P(B_1 \mid V) = \frac{(1/2)\, (3/4)}{(5/8)} = 3/5 $$

#### Diachronic Bayes (related to change over time)

H = hypothesis (prior)
D = Body of data

$$ P(H \mid D) = \frac {P(H) \, P(D\mid H)}{ P(D)} $$

Portions of the equation:

Prior is the probability of the data before we see the hypothesis: $$ P(H) $$

Posterior is the probability of the hypothesis after we see the data: $$ P(H \mid D) $$

Likelihood is the probability of the data under the hypothesis: $$ P(D \mid H) $$

Total probability of the data is: $$ P(D) $$

As in the previous example, we can compute $$ P(D) $$

using the law of total probability. For example with two hypotheses:

$$ P(D) = P(H_1) \, P(D \mid H_1) + P(H_2) \, P(D \mid H_2) $$

or with any number of hypotheses:

$$ P(D) = \sum_ {i} P(H_i) \; P(D \mid H_i) $$

#### Bayes Tables

In [1]:
import pandas as pd

table = pd.DataFrame(index=['Bowl 1', 'Bowl 2'])

table['prior'] = 1/2, 1/2
table

        prior
Bowl 1    0.5
Bowl 2    0.5

In [2]:
table['likelihood'] = 3/4, 1/2
table

        prior  likelihood
Bowl 1    0.5        0.75
Bowl 2    0.5        0.50

In [3]:
table['unnorm'] = table['prior'] * table['likelihood']
table

        prior  likelihood  unnorm
Bowl 1    0.5        0.75   0.375
Bowl 2    0.5        0.50   0.250

Calling them 'unnorm' because they are unnormalized posteriors, the product of a prior and a likelihood 

$$ P(B_i) \, P(D \mid B_i) $$

which is the numberator of Bayes's theorem.

If you add them up, 

$$ P(B_1) \, P(D \mid B_1) + P(B_2) \, P(D \mid B_2) $$

you have the denominator, 

$$ P(D) $$

In [4]:
# Let's compute total probability 

prob_data = table['unnorm'].sum()
prob_data

np.float64(0.625)

In [5]:
# and posterior probabilities

table['posterior'] = table['unnorm'] / prob_data
table

        prior  likelihood  unnorm  posterior
Bowl 1    0.5        0.75   0.375        0.6
Bowl 2    0.5        0.50   0.250        0.4

Here we have found the posterior probabilities of both bowls having drawn a vanilla!

#### The Dice Problem

A Bayes table can also solve problems with more than two hypotheses. Consider this example:

- I have a box with a 6-sided, 8-sided, and 12-sided die. If you choose one of the die at random, roll it, and find that you have rolled a 1, what is the probability that you have chose the 6-sided die?

In this example, you have three hypotheses with equal prior probabilities (just as likely that you drew from the box the 6, 8, or 12-sided die). 

However, the data (rolling a "1") gives us new insights.

In [6]:
table2 = pd.DataFrame(index=[6,8,12])

In [7]:
from fractions import Fraction

table2['prior'] = Fraction(1,3)
table2['likelihood'] = Fraction(1,6), Fraction(1,8), Fraction(1,12)
table2

   prior likelihood
6    1/3        1/6
8    1/3        1/8
12   1/3       1/12

In [8]:
def update(table):
    table['unnorm'] = table ['prior'] * table ['likelihood']
    prob_data = table ['unnorm'].sum()
    table['posterior'] = table ['unnorm'] / prob_data
    return prob_data

prob_data = update(table2)

table2

   prior likelihood unnorm posterior
6    1/3        1/6   1/18       4/9
8    1/3        1/8   1/24       1/3
12   1/3       1/12   1/36       2/9

We can see here with our posteriors that the 6-sided die is most likely because drawing a 1 on that die has highest likelihood in our table.

#### The Monty Hall Problem

Consider this example:

- You see three numbered doors with a prize behind one of them.
- The objective of the game is to choose the door with the prize.
- After selecting a door, one of the remaining doors is opened to show no prize behind it.
- You are given the option to switch your selected door.

To maximize your chance of winning the prize, do you stick with your selected door or choose the remaining door?

In [9]:
table3 = pd.DataFrame(index=['Door 1', 'Door 2', 'Door 3'])
table3['prior'] = Fraction(1,3)
table3

       prior
Door 1   1/3
Door 2   1/3
Door 3   1/3

In [10]:
table3['likelihood'] = Fraction(1,2), 1, 0
table3

       prior likelihood
Door 1   1/3        1/2
Door 2   1/3          1
Door 3   1/3          0

In [11]:
# now let's use the update function
update(table3)
table3

       prior likelihood unnorm posterior
Door 1   1/3        1/2    1/6       1/3
Door 2   1/3          1    1/3       2/3
Door 3   1/3          0      0         0

#### Exercises

In [12]:
#2-1

import pandas as pd

table = pd.DataFrame(index=['coin 1', 'coin 2'])

table['prior'] = 1/2, 1/2

table['likelihood'] = 1/2, 1

table['unnorm'] = table['prior'] * table['likelihood']

prob_data = table['unnorm'].sum()

table['posterior'] = table['unnorm'] / prob_data
table

        prior  likelihood  unnorm  posterior
coin 1    0.5         0.5    0.25   0.333333
coin 2    0.5         1.0    0.50   0.666667

In [13]:
#2-2
table = pd.DataFrame(index=['BB', 'BG/GB', 'GG'])

table['prior'] = 1/3, 1/3, 1/3

table['likelihood'] = 0, 1/2, 1/2

table['unnorm'] = table['prior'] * table['likelihood']

prob_data = table['unnorm'].sum()

table['posterior'] = table['unnorm'] / prob_data
table

          prior  likelihood    unnorm  posterior
BB     0.333333         0.0  0.000000        0.0
BG/GB  0.333333         0.5  0.166667        0.5
GG     0.333333         0.5  0.166667        0.5

In [15]:
#2-3
# Part 1
table3 = pd.DataFrame(index=['Door 1', 'Door 2', 'Door 3'])
table3['prior'] = Fraction(1,3)

table3['likelihood'] = Fraction(1,3), (2/3), 0

update(table3)
table3

       prior likelihood    unnorm posterior
Door 1   1/3        1/3       1/9  0.333333
Door 2   1/3          0         0       0.0
Door 3   1/3   0.666667  0.222222  0.666667

In [16]:
# Part 2
table3 = pd.DataFrame(index=['Door 1', 'Door 2', 'Door 3'])
table3['prior'] = Fraction(1,3)

table3['likelihood'] = 0, 1, 0

update(table3)
table3

       prior  likelihood unnorm posterior
Door 1   1/3           0      0         0
Door 2   1/3           1    1/3         1
Door 3   1/3           0      0         0

In [17]:
#2-4
table = pd.DataFrame(index=['Y94G96', 'G94Y96'])

table['prior'] = 1/2, 1/2

table['likelihood'] = 1/25, 7/500

table['unnorm'] = table['prior'] * table['likelihood']

prob_data = table['unnorm'].sum()

table['posterior'] = table['unnorm'] / prob_data
table

        prior  likelihood  unnorm  posterior
Y94G96    0.5       0.040   0.020   0.740741
G94Y96    0.5       0.014   0.007   0.259259